### ISSUE TITLE
Link '...indigo-dc/udocker/master/messages' returns 404 not found

### ISSUE THREAD

**Issue by muttleyxd** [indigo-dc/udocker#166]
I cant install udocker, `udocker --install` fails with this
```
Info: getting file: https://raw.githubusercontent.com/indigo-dc/udocker/master/messages
Error: in download:  HTTP/1.1 404 Not Found :  0
Warning: in install information: [Errno 2] No such file or directory: '' 
```

When I enter this link it returns '404: Not Found'

Edit: I tried installing newest version from GitHub, as stated in `installation_manual.md`

**Comment by mariojmdavid** [comment]
it's 
udocker install

**Comment by jorge-lip** [comment]
That is not an installation error, that looks like you are running udocker with debugging enabled 
or with a higher level of verbosity set, that's why you see that download error. 
The failure to download https://raw.githubusercontent.com/indigo-dc/udocker/master/messages
does not affect the installation and is not a problem.

  curl https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py > udocker
  chmod u+rx ./udocker
  ./udocker install

The additional verbosity can be caused by using --debug or -D in the command line or by having
the env variable UDOCKER _LOGLEVEL set, or by having the loglevel set in a udocker.conf file 
in one of these locations /etc, $HOME/.udocker or in /home.

**Comment by muttleyxd** [comment]
Okay, I've got it working, what was confusing me that ./udocker install returned 1 instead of 0, despite it was working correctly.
