### ISSUE TITLE
Use docker-py instead of own Docker API client

### ISSUE THREAD

**Issue by multimeric** [indigo-dc/udocker#177]
I notice that a lot of code is devoted to re-implementing a Docker API client. Is there any interest in using an external python library for this, such as [docker-py](https://github.com/docker/docker-py). I suspect this would give us some free advantages, like compatibility with the `image@sha256` syntax (#112). I would be happy to look into making a PR if there is.

**Comment by katakombi** [comment]
What impact would this have on dependencies? Being able to use `image@sha256` would be great, but I'm worried of having many additional dependencies. To me it is important that udocker simply runs everywhere due to having almost no dependencies, and self-containing everything it requires at runtime.

**Comment by TMiguelT** [comment]
It would mean adding a proper python/pip dependency, yes. But the docker-py package is pure python, so it will work on any OS/python version (https://pypi.org/project/docker-py/#files). In addition, making udocker a proper python package would mean you could simply `pip install udocker` and you could run the executable, instead of the current (much longer) install process:
```
 curl https://download.ncg.ingrid.pt/webdav/udocker/udocker-1.1.2.tar.gz > udocker-tarball.tgz
  export UDOCKER_TARBALL=$(pwd)/udocker-tarball.tgz
  tar xzvf $UDOCKER_TARBALL udocker
  ./udocker install
  mv ./udocker $HOME/bin/   # move the executable to your preferred location for binaries
```

**Comment by katakombi** [comment]
I can't speak in the interest of the udocker devs but IMO the current installation process is deliberately designed to be as it is. 
I'd believe that by using this tar-ball which is being hosted redundantly on several fallback locations they ensure that any old udocker releases will work OOTB even after years.
I doubt that this can be ensured when `pip` is being involved since it offers kinda rolling releases.
I might be mistaken, just my guess... 
And I would be curious to read a statement from those who are involved in development.

**Comment by cswl** [comment]
`Connect to Docker using the default socket or the configuration in your environment:`
```
import docker
client = docker.from_env()
```

Does it work without connecting to a already running docker socket?

**Comment by mariojmdavid** [comment]
udocker is kept with a minimal number of dependencies, and none whatsoever from pypi, relies only on the python standard library
although udocker is in pypi

we will close this issue, but feel free to re-open if you want to discuss further
