### ISSUE TITLE
PyPI version broken

### ISSUE THREAD

**Issue by SpheMakh** [indigo-dc/udocker#198]
The version PyPI is broken. Could you please make a release of the current master on PyPI

**Comment by mariojmdavid** [comment]
hi
this is known, we have made a mistake when uploading the current prod version to pypi, we expect to solve this in the next release of udocker
due to some pypi feature, when a version is uploaded, even if we delete it, it does not allow the same version anymore, and that is why we could not have fixed it

**Comment by SpheMakh** [comment]
Do you have an ETA for when you will make a new release?

**Comment by SpheMakh** [comment]
Since the current release is broken, I think you should make it ASAP because packages that depend on udocker cannot make releases also until you do. This is a very annoying situation

**Comment by mariojmdavid** [comment]
hi @SpheMakh , apologies for the delay
please check and try now
pip install udocker
you will get version 1.1.3-post1, but is exactly the same released version (1.1.3), we just fix the setup.py and upload to pypi
