### ISSUE TITLE
singularity file binds leaves target files/paths inside the container

### ISSUE THREAD

**Issue by katakombi** [indigo-dc/udocker#240]
Thanks a lot for implementing file binds in S1 mode in `devel`!
I can see that target files (and directories) are not being deleted after the binding process in the container is being terminated. I think this should be possible, am I right?
Udocker just needs to keep track on what it had created initially.

**Comment by jorge-lip** [comment]
That's intentional. checking and removing the mountpoints is not an atomic a operation.
If a container is being executed in another cluster host we can get trouble if one instance is in the middle of removing while other is in the middle of mounting.
The mountpoints are removed when you convert to another execution mode or with:

udocker setup --purge

**Comment by katakombi** [comment]
Thanks for the explanation! Closing therefore...
