### ISSUE TITLE
proot info: pid 32755: terminated with signal 6

### ISSUE THREAD

**Issue by jimonreal** [indigo-dc/udocker#262]
When I run my container in my own machine I have no issue with the execution.
However, running the same exact container using the same udocker in another machine (cluster) I get the following output:

proot info: pid 32755: terminated with signal 6
proot info: pid 32757: terminated with signal 6
proot info: pid 32756: terminated with signal 6
proot info: pid 32754: terminated with signal 6
proot info: pid 32753: terminated with signal 6
proot info: pid 32752: terminated with signal 6
proot info: pid 32751: terminated with signal 6
proot info: pid 32750: terminated with signal 6
proot info: pid 32749: terminated with signal 6
proot info: pid 32748: terminated with signal 6
proot info: pid 32747: terminated with signal 6
proot info: pid 32746: terminated with signal 6
proot info: pid 32745: terminated with signal 6
proot info: pid 32744: terminated with signal 6
proot info: pid 32743: terminated with signal 6
proot info: pid 32742: terminated with signal 6
proot info: pid 32741: terminated with signal 6
proot info: pid 32740: terminated with signal 6
proot info: pid 32739: terminated with signal 6
proot info: pid 32738: terminated with signal 6
proot info: pid 32737: terminated with signal 6
proot info: pid 32736: terminated with signal 6

uname -r
2.6.32-754.17.1.el6.x86_64

ldd --version
ldd (GNU libc) 2.12

Any idea why this happens?

What other information can I post that could help you guys help me find the problem?
Last year when running udocker I didn't have this problem.

**Comment by mariojmdavid** [comment]
do you create the container in the cluster node, before running it?
udocker create ...
udocker run ...

what docker image you are using

**Comment by jimonreal** [comment]
I created the container in my local machine with docker and then exporting it.
The base image is openjdk:8-jdk-slim

**Comment by mariojmdavid** [comment]
you should create the container in the machine where it is going to run, the execution modes, specially proot, are based on the libraries and paths of the underlying host machine, and specially if you have different operating systems (i.e. centos7 in you laptop, and centos6 in the cluster), the container created in your laptop will not work on the cluster machine, since the container will have references and paths of your original laptop OS

as I said previously, if you are running a job in some cluster you should have something like

udocker create --name=<cont_name> <docker image name>
udocker run <cont_name>

**Comment by jimonreal** [comment]
Thanks Mario, I will try that!

**Comment by jimonreal** [comment]
So If I get an image from the dockerhub, how is that different? Also, how can I create a container with udocker and a Dockerfile?

**Comment by jimonreal** [comment]
> you should create the container in the machine where it is going to run, the execution modes, specially proot, are based on the libraries and paths of the underlying host machine, and specially if you have different operating systems (i.e. centos7 in you laptop, and centos6 in the cluster), the container created in your laptop will not work on the cluster machine, since the container will have references and paths of your original laptop OS
> 
> as I said previously, if you are running a job in some cluster you should have something like
> 
> udocker create --name=<cont_name>
> udocker run <cont_name>

This also does not make sense, as I used to run the containers the same way before. Just now, that the dockerhub images have been updated, and the glibc seems to be the problem.

**Comment by mariojmdavid** [comment]
apologies if you already know this
the docker image is the entity that is stored in dockerhub or on your machine or laptop etc.
when you have a Dockerfile and issue a build it builds an image, udocker does not support build of docker images because that's in general done by docker itself, and can be done on any system you have sufficient privileges.

the container is the instantiation of an image into a running process, and this is what you want to run.

if you do
udocker pull <docker_image> # it pulls a given image from dockerhub

if now you do
udocker run <docker_image>
it does 2 things it create a container (instantiate a image) *and* it run that "container"

that is equivalent to
udocker create....
udocker run <container_name>

for the possible error of glibc, let me try on a VM with centos6, 
tell me what you are trying to run with the image openjdk:8-jdk-slim
so I can try to reproduce or test
best

**Comment by jimonreal** [comment]
I am running a custom code, which uses 2 simulators. I can post the verbose log of udocker below:


```
Warning: non-existing user will be created
CMD = ['/home/users/monrealj/.udocker/bin/proot-x86_64', '--kill-on-exit', '-b', '/home/users/monrealj/Scenarios/scenario/routing/4/1/60/no/0.8/fcd:/opt/simrunner/sumoCfg/scenario/routing/4/fcd', '-b', '/home/users/monrealj/Scenarios/scenario/routing/4/1/60/no/0.8/msgs:/opt/simrunner/sumoCfg/scenario/routing/4/msgs', '-b', '/home/users/monrealj/Scenarios/scenario/routing/4/1/60/no/0.8/results:/opt/simrunner/sumoCfg/scenario/routing/4/results', '-b', '/home/users/monrealj/Scenarios/scenario/routing/4/1/60/no/0.8/summary:/opt/simrunner/sumoCfg/scenario/routing/4/summary', '-b', '/home/users/monrealj/Scenarios/scenario/routing/4/1/60/no/0.8/logs:/opt/simrunner/sumoCfg/scenario/routing/log', '-b', '/dev:/dev', '-b', '/proc:/proc', '-b', '/sys:/sys', '-b', '/etc/resolv.conf:/etc/resolv.conf', '-b', '/etc/host.conf:/etc/host.conf', '-b', '/lib/modules:/lib/modules', '-b', '/tmp/udocker-2996-7b41ba4a-a1b7-3ff5-bafa-1726488a1f40-passwd:/etc/passwd', '-b', '/tmp/udocker-2996-9b8819cd-ed7a-36ee-9564-c35bf5ddd437-group:/etc/group', '-0', '-k', '6.0.0', '-r', '/home/users/monrealj/.udocker/containers/ba769659-1faa-3322-8272-efd1736eeed9/ROOT', '-w', u'/opt/simrunner', u'/opt/simrunner/startup.sh', 'java', 'PrepareAndExecuteRunner', 'sumoCfg/scenario/routing/4', 'no', '60', '1', '4800m', '19557', '0.8', '0.8']

 ******************************************************************************
 *                                                                            *
 *               STARTING ba769659-1faa-3322-8272-efd1736eeed9                *
 *                                                                            *
 ******************************************************************************
 executing: startup.sh
proot info: pid 3111: terminated with signal 6
proot info: pid 3112: terminated with signal 6
proot info: pid 3110: terminated with signal 6
proot info: pid 3109: terminated with signal 6
proot info: pid 3108: terminated with signal 6
```

and log level 5 is too verbose, if you need it I can upload it

**Comment by jorge-lip** [comment]
This issue is too old and is an upstream PRoot issue.
