### ISSUE TITLE
add ability to rewrite the ENTRYPOINT

### ISSUE THREAD

**Issue by vykozlov** [indigo-dc/udocker#306]
Sometimes it might be useful to define an ENTRYPOINT in the Docker image, or some Docker images already have it.
For debugging, however, it might be practical to overwrite the entrypoint with e.g. /bin/bash. The standard docker command has this feature as:

docker run --entrypoint=/bin/bash

Unfortunately, there is no similar functionality in udocker. This could be a nice enhancement.

BTW, 'udocker run' has "--nometa" flag which helps, i.e. skips the defined ENTRYPOINT, but it also seem to reset some other metadata, which can be useful.

**Comment by microbioticajon** [comment]
I have literally just run into exactly the same issue!

**Comment by microbioticajon** [comment]
Ah... maybe not... sorry for the noise...

**Comment by microbioticajon** [comment]
I had a quick look at this. There is an --entrypoint option in udocker.py at:
https://github.com/indigo-dc/udocker/blob/775308bfdc10c7d67c221ed62e1f401449a327fd/udocker.py#L7738

The best I could tell from the code is that if "entryp" is set as a string it will completely overwrite the command with that value and discard any other "cmd" values:
https://github.com/indigo-dc/udocker/blob/775308bfdc10c7d67c221ed62e1f401449a327fd/udocker.py#L2734

However, if "entryp" reaches this point as an array it will try to incorporate the rest of the run command "cmd" values as parameters.


In my case, I wanted to do this:

`udocker run --rm -v /tmp/scripts:/tmp/scripts randomDockerImageWithEntrypoint:latest /bin/bash /tmp/scripts/my_script.sh `

The docker image I want to use is built with an entrypoint that the script itself calls - I need to override this...

If I try to reset the entrypoint as docker suggests (https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime):

`udocker run --rm -v /tmp/scripts:/tmp/scripts --entrypoint="" randomDockerImageWithEntrypoint:latest /bin/bash /tmp/scripts/my_script.sh`

the builtin entrypoint fires rather than the command I specify on the command line.

If I try:

`udocker run --rm -v /tmp/scripts:/tmp/scripts --entrypoint=/bin/bash randomDockerImageWithEntrypoint:latest /tmp/scripts/my_script.sh`

the script is not executed - it just runs bash.

However if I try:

`udocker run --rm -v /tmp/scripts:/tmp/scripts --entrypoint="/bin/bash /tmp/scripts/my_script.sh" randomDockerImageWithEntrypoint:latest`

my_script.sh fires - hurra!

Perhaps Im missing something, but this feels like udocker entrypoint handling does not match that of Docker.

Best,
J

**Comment by jorge-lip** [comment]
A fix is provided in v1.3.0. https://github.com/indigo-dc/udocker/releases/tag/v1.3.0
