### ISSUE TITLE
[joss-review] paper review

### ISSUE THREAD

**Issue by vsoch** [indigo-dc/udocker#312]
The paper does a good job of introducing the software, and explaining the use case. Since some readers (like myself) are probably familiar with udocker, I'd want to know beyond "several new features" how this new release is different, and more importantly, why it warrants a new paper. For the latter, we should have that discussion here or in the main review (not in the paper).

https://github.com/openjournals/joss-reviews/issues/3295

**Comment by jorge-lip** [comment]
We lust released 1.3.0 and we added anew section to the paper with the most relevant changes since 1.1.1
when it was initially published.

**Comment by vsoch** [comment]
Thank you! I'm reading now and I have a few suggestions:

> Support for OCI containers format was added.

OCI has several standards for containers - could you clarify in the paper what "OCI containers format" is referring to?

> The udocker implementation of the Docker Hub API was reim-77plemented and support for the Docker Hub v2 API was added.

It's confusing that this line follows the line about OCI - the "Docker Hub V2 API is the OCI distribution spec." If there is some variance between those two, what is it?

> The verification of containers78images including checksumming was also implemented

When and how does this happen?

> The search functionality was reimplemented

How? Is it better/faster/something else?

> Support for v1 and v2 repositories and listing of tags was added. 

I don't think the average reader will know what v1/v2 repositories are.

> The command line was significantly improved fixing many of the original lim-82itations.

Like?

Ill stop copy pasting line by line - this feels like you copy pasted lines from a changelog, and it reads very robotically and is not friendly to the reader, who might not know some of these technical references, and if they do, there isn't enough detail to understand what was really done (e.g., saying "was fixed or was implemented" doesn't really tell me much.

Since the entire purpose of this new publication is for these significant updates, I'd like to see them possibly more fleshed out so I can read the paper and it's sufficient to understand the changes.

**Comment by mviereck** [comment]
I second this.
The basic need and advantage of udocker as a container solution for unprivileged users is clearly stated.
Though, this goes for the udocker version of the first paper, too.
There has been some development and improvement since then; though, I still don't see a major difference.

Maybe it helps to change the perspective:
If someone writes a scientific paper and wants to cite udocker: at which point he would have the _urgent  need_  to cite the new paper instead of the previous one?

**Comment by vsoch** [comment]
That’s a good idea @mviereck !

**Comment by mviereck** [comment]
For refererence, a link to the udocker paper of 2018:
https://www.sciencedirect.com/science/article/pii/S0010465518302042

**Comment by mviereck** [comment]
@jorge-lip Thank you for rewriting the chapter about the differences to version 1.1.
For now I am a bit overwhelmed by the length of the text. Will read it again.

Can you describe the difference in a nutshell, in a few sentences that nail down to the point? Less going into several technical details, but rather from a meta perspective?

**Comment by mviereck** [comment]
Could you please answer these questions?

> If someone writes a scientific paper and wants to cite udocker: at which point he would have the urgent need to cite the new paper instead of the previous one?

Similar, but not the same:

> Can you describe the difference in a nutshell, in a few sentences that nail down to the point? Less going into several technical details, but rather from a meta perspective?

**Comment by danielskatz** [comment]
ref: https://github.com/openjournals/joss-reviews/issues/3295

**Comment by jorge-lip** [comment]
Since 1.1.1, udocker moved from a proof of concept tool suitable for production. The focus has been put on sustainability and interoperability. The code structure was redesigned moving from the Python 2 monolithic code to a new Python 3 modular implementation. New features and improvements were added to support a wider range of Linux distributions and environments. To this end the execution engines now support `crun` for namespace based execution with `cgroups v2` and a port of `Fakechroot` to support `MUSL libc`. The existing execution engines were also enhanced to address the shortcomings present in the proof of concept and improve interoperability for execution across a wider range of distributions, kernels and better supporting the functionalities required for containers execution.  Support for multiple architectures was added and binaries for ARM and x86 are now provided for `PRoot` based execution, further binaries can be easily added as needed. Support for accelerated computing was implemented by introducing the capability to setup containers to use NVIDIA GPUs according to the host environment and across the several execution engines. The handling of container images was improved both at the level of interaction with container registries and handling of formats. The interaction with registries is now more interoperable and robust and support for the OCI image specification v1 was introduced. Furthermore the search capabilities support docker registry v1 and v2 specifications and listing of tags. The command line interface and configuration was improved with new commands, flags and better parsing of both the command line and config files. Finally the installation of the tools and libraries was decoupled from udocker itself, both can now be released separately. The shared installation of udocker in distributed filesystems was addressed with changes introduced to handle the cases where udocker is executed from readonly filesystems. Finally, udocker is now also available from *PyPI*. A more complete description is provided in the paper.

**Comment by mviereck** [comment]
Thanks.
This is more comprehensive than the current chapter in the paper that contains a lot of detail that does not belong there, like e.g. API documentation.
I suggest to replace it with this summary.

>  If someone writes a scientific paper and wants to cite udocker: at which point he would have the urgent need to cite the new paper instead of the previous one?

So far udocker got a lot of maintenance towards a better code base and broader support of different environments. The essential idea and concept is still the same and fits the description in the first paper. So there is basically no need for a new paper except to provide a recent version number.

**Comment by mariojmdavid** [comment]
paper rejected, closing
