### ISSUE TITLE
udocker cannot load my image.tar created by docker save (failed to extract container)

### ISSUE THREAD

**Issue by Root-voidX** [indigo-dc/udocker#361]
When I try to use udocker load -i I get this error:

```
 ai-fe  qemu  ~  udocker --version
version: 1.3.2
tarball: https://download.ncg.ingrid.pt/webdav/udocker/udocker-englib-1.2.8.tar.gz https://raw.githubusercontent.com/jorge-lip/udocker-builds/master/tarballs/udocker-englib-1.2.8.tar.gz
tarball_release: 1.2.8

 ai-fe  qemu  ~  udocker load -i CentOS-7-DockerImage
CentOS-7-DockerImage/    CentOS-7-DockerImage.7z  

 ai-fe  qemu  ~  udocker load -i CentOS-7-DockerImage/CentOS-7-DockerImage.tar 
Error: failed to extract container: CentOS-7-DockerImage/CentOS-7-DockerImage.tar
Error: load failed

```

**Comment by mariojmdavid** [comment]
hi
can you tell me which linux distro you are using?
I have tested this successfully in my desktop ubuntu22.04

```bash
docker save centos:7 -o centos7.tar
mkdir somedir
mv centos7.tar somedir/
udocker load -i somedir/centos7.tar 
udocker images
REPOSITORY
centos:7   
```

**Comment by fcasson** [comment]
We found a similar issue for CentOS and Rockylinux tarballs which contain some layers referenced as symlinks.  I think this behaviour may have arisen with newer versions of docker or udocker, since we did not have it in the past.

`udocker verify` points to the problem layers which can be seen in the tarball to be the symlink layers

Two workarounds
- Avoid the tarball with `docker save ${NAME} | udocker load -`
- Rewrite the tarball without symlinks (I have a script for this)
