### ISSUE TITLE
Skip installation

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [indigo-dc/udocker#376]
We're using docker in AWS Lambda, so we're using `udocker/udocker` to execute commands.

Before executing any cmd the script is trying to install docker, as we're directly using the executables, is there any existing ways to skip the installation?

https://github.com/indigo-dc/udocker/blob/bd523eab3d5557a3d49c6583b5c3fe8b36212c38/udocker/umain.py#L105-L106

@jorge-lip @mariojmdavid

**Comment by jorge-lip** [comment]
During the installation udocker downloads and installs the binaries that support the execution engines, these are required for udocker to execute containers. Therefore skipping the installation does not make much sense. What you may want to do is to install the binaries from a local tarball instead of downloading from the network. See the manual:

https://github.com/indigo-dc/udocker/blob/master/docs/installation_manual.md#24-install-without-outbound-network-access

**Comment by DilLip-Chowdary-Codes** [comment]
I've added those required binaries in the `UDOCKER_BIN` location, so here my container is working properly.

Here I'm getting an n/w error in the installation, currently, I'm ignoring it, now I want to disable this installation process.

**Comment by jorge-lip** [comment]
Then you also need the lib directory with the VERSION file having as content the string of the udocketools version that is 1.2.8
Just install udocker in the normal fashion somewhere and copy $HOME/.udocker/lib/VERSION

**Comment by DilLip-Chowdary-Codes** [comment]
It worked, thanks.

mentioned the older version previously.
